version:  '3'

services:
  builder: 
    build: docker/builder
    volumes:
      - ./src/ts:/usr/src/app
    restart: always
    tty: true
  # main:
  #   build: .
  #   volumes:
  #     - ./src:/usr/src/app
  #     #- /usr/src/app/node_modules # if need access to container volumes
  #   restart: always
  #   tty: true
  #   command: sh